### ISSUE TITLE
Undersøg react native

### ISSUE THREAD

**Issue by FrederikVil** [allahsoftdk/allahsoft-react-native-app#4]
Der skal undersøges om react native

**Comment by Isaacvorkoper** [comment]
@FrederikVil Poopy-di scoop
Scoop-diddy-whoop
Whoop-di-scoop-di-poop
Poop-di-scoopty
Scoopty-whoop
Whoopity-scoop, whoop-poop
Poop-diddy, whoop-scoop
Poop, poop
Scoop-diddy-whoop
Whoop-diddy-scoop
Whoop-diddy-scoop, poop
